### ISSUE TITLE
Kostal login flow

### ISSUE THREAD

**Issue by maigl** [ITTV-tools/kostalplenticorepy#13]
Hi, thanks for this awesome lib.

 I was wondering if you guys know what kind of login flow that is ?
Is this some standardized algorithm? I'm trying to login in my go app.
I can translate your python code to go. But if this is a common algorithm then there probably already is a library for this.

Thanks 

maigl

**Comment by ITTV-tools** [comment]
Hi,
youre welcome. 

I dont really now. I only adopted it from Java to Python. From Fhem 
https://wiki.fhem.de/wiki/Kostal_Plenticore_10_Plus#Plenticore_API

**Comment by maigl** [comment]
:laughing:  okay .. well then I will just translate it into go .. maybe one day we'll find someone how knows!
